### ISSUE TITLE
Consider adding source repository references in the index files

### ISSUE THREAD

**Issue by waynebeaton** [jakartaee/specifications#114]
This is useful information that might help drive contribution.

**Comment by kwsutter** [comment]
This is a funny coincidence...  As I was trying to clean up some older Issues, I was looking at the Specification record for Interceptors to see if I could determine the name of the repo...  Nope, not there...  And, then I opened this Issue and see that you had the same idea.  We should consider this for the Jakarta EE 9 effort and then possibly backport it to the Jakarta EE 8 artifacts as well.  Thanks.

**Comment by bshannon** [comment]
Note that you'll find an index to all the repos on the [Specifications](https://eclipse-ee4j.github.io/jakartaee-platform/Specifications) page.

**Comment by ivargrimstad** [comment]
I think this one has been lingering long enough. All the repositories are reachable through the "Project" link on the top of each specification page. The link is to the PMI pages where all resources associated with the project are listed.
