### ISSUE TITLE
Concurrency (JSR-236) is problematic in practice. Pls rework the API and fully support CDI.

### ISSUE THREAD

**Issue by Tibor17** [jakartaee/specifications#129]
I reported issues against the Wildfly due to this API is not practical in commercial EE world but the issues were closed due to the problem is here in the Spec.
The developer wants to execute Task as a Bean in the ThreadPool.
If you have a producer of EntityManager, these Task beans won't see it!
You won't be able to use the scopes because they do not have the end in the Thread and therefore the JDBC connection is permanently open.
Pls support using CDI beans and scopes in the concurrent Task beans without any additional need to construct them via Proxy, etc.

I like to have JSR 236, that's why my company used it, but in another fashion, I would say, and in more EE Beans Context friendly style which would speedup my s/w development of the projects.

 Perhaps the dev community should re-evaluate the classes in `javax.enterprise.concurrent`, see [1], and differentiate between internal needs (for e.g. Async in `JAX-RS` and application servers) and the external needs in the users community. Me as a user expected this API in JSR 236 to fulfil my needs in order to schedule Tasks in `ManagedScheduledExecutorService` instead of doing it in EJB Timer, of course the ThreadPool should understand the CDI context because my company is using the CDI.

[1]: https://javaee.github.io/javaee-spec/javadocs/javax/enterprise/concurrent/package-summary.html 

As i said before I have problem with the way how the beans (via proxy) in JSR 236 are used in terms of beans context. I am still pointing to the practicle use.

The JSR 236 was found as a substitution of EJB Timer but again it had problems with Beans Context, strange Proxying style, strange way to enable transactions, etc.
It would be enough to say in the spec that the `Managed*ExecutorService` should be able to work with CDI beans with Application scope and Request scope and then Jakarta EE can remove `ContextService`, `"executionProperties"`.
Internally, the application server may still have to use the `ManagedExecutorService` (not appear in JavaDoc) but the enduser may prefer (should be in JavaDoc) another API, something like this:

```
@RequestScoped
public class ShortLifecycleBean implements Runnable {
  @Inject EntityManager em;

  public void run() { ... }
}

@Resource
ManagedScheduler<ShortLifecycleBean> scheduler;

// NOTICE: the Runnable is not in the first parameter because the ManagedScheduler
// will "call us and we will NOT pass our bean to ManagedScheduler" => IoC
Future<?> f = scheduler.schedule( trigger );
```

Therefore the new interface `ManagedScheduler` is the manager (IoC) of the beans again!

**Comment by keilw** [comment]
@Tibor17 I know the different organizations can be confusing at times for many outside the Jakarta Working Groups, but in such detail, there is no point raising it here either.

Please try https://github.com/eclipse-ee4j/concurrency-api/issues. It seems the "Transfer issue" feature won't work between "jakartaee" and "eclipse-ee4j", so as this is clearly something for the API project, if you believe you can help them improve things, please recreate it there.

**Comment by smillidge** [comment]
I copied the issue over to the Concurrency API project
