### ISSUE TITLE
Jakarta EE 8 challenge, permissions.xml must also be added to EAR level

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/specifications#131]
Hi,

A few months ago, I created a TCK challenge [Jakarta-tck issue#132](https://github.com/eclipse-ee4j/jakartaee-tck/issues/132) that has been addressed in the Jakarta TCK project source and should be included in the 8.0.2 Platform TCK.

I'm opening this issue now, to represent the challenge, as required by the [TCK process document](https://github.com/jakartaee/specification-committee/blob/master/process.adoc#filing-a-challenge), as we should follow the defined process.

[Since the TCK is already updated to address this challenge](https://github.com/eclipse-ee4j/jakartaee-tck/commit/3457ef2e04445708d82b1f3300f457625e9427f6), the challenge should be accepted.  This is not exactly the action suggested by the [TCK process document](https://github.com/jakartaee/specification-committee/blob/master/process.adoc#filing-a-challenge), so perhaps the process document should be amended to allow resolution via code changes as well as test exclusion?

**Comment by starksm64** [comment]
I would think we would still want a challenge as the basis for justifying a code change no? It looks like there was some failing behavior that warranted the tck #132 issue. Perhaps we can say that a bug report with a code change that also has a challenge label can be accepted in place of a challenge specific issue.

**Comment by scottmarlow** [comment]
I agree with the idea of amending to say that a bug report with a code change that also has a challenge label can be accepted in place of filing the challenge with the specification project’s issue tracker.

A separate issue is that I couldn't add a label to this issue (#131).  I'm not sure if this is a permission issue or if we just need to create some labels (challenge, challenge-appeal).

**Comment by bshannon** [comment]
I thought we decided that only exclusions would be allowed in TCK updates that target the current spec version, and that code changes would have to be in a TCK version that targets the next spec version.

Or, code changes targeting the current spec version have to be done in such a way that they do not invalidate any existing Compatibile Implementation that passed the existing TCK.

**Comment by scottmarlow** [comment]
Bill, so to keep with the current TCK process, we could release TCK 8.0.2 with the challenged test excluded.  I didn't expect the [jakartaee-tck/issues/132](https://github.com/eclipse-ee4j/jakartaee-tck/issues/132) to invalidate any existing Compatible Implementations but I don't really know that for sure.

**Comment by scottmarlow** [comment]
Opened [jakartaee-platform/issue#139](https://github.com/eclipse-ee4j/jakartaee-platform/issues/139) for the challenge, closing this one, as I don't think it is needed for the challenge.
