### ISSUE TITLE
Are the implementation links supposed to point to the spec itself in the Jakarta EE 9 specs for now?

### ISSUE THREAD

**Issue by keilw** [jakartaee/specifications#148]
It seems almost every Jakarta EE 9 spec has the same links like
https://jakarta.ee/specifications/security/2.0/
where "Compatible Implementations" only points to "Jakarta Security" which is the spec page itself.

Is that intentional? Or only going to switch later?

**Comment by ivargrimstad** [comment]
I think it is intentional since the version of the compatible implementation (in this case Soteria) is not ready yet, hence the markdown contains an empty link which is rendered as a link to the current page.
