### ISSUE TITLE
Receive Date is not populating for some emails

### ISSUE THREAD

**Issue by bibhutik** [jakartaee/specifications#174]
It  is our observation for some emails the received date is not populating. Also, we observed this happening for char set as below.

Content-Type: text/html; charset="x-iscii-ta" 

The issue is observed on version 1.6.5 also

**Comment by kwsutter** [comment]
@bibhutik, is this Issue related to Jakarta Mail?  If so, we can get it transferred.  Just trying to clarify which component this is targeting.  Thanks!

**Comment by ivargrimstad** [comment]
This has been hanging around for so long that I think we may close it.
