### ISSUE TITLE
[batch] Insecure mixed content detected

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/specifications#184]
Netlify detected some content that’s being served over an HTTP connection in specifications/batch/2.0/batch-spec-2.0.html:

Insecure img urls:

- http://static.springsource.org/spring-batch/trunk/reference/html-single/images/job-heirarchy.png

- http://static.springsource.org/spring-batch/trunk/reference/html-single/images/jobHeirarchyWithSteps.png

- http://static.springsource.org/spring-batch/trunk/reference/html-single/images/chunk-oriented-processing.png

**Comment by kwsutter** [comment]
Hi @chrisguindon.  Is there any chance that these type of warnings could be posted to the PR that caused the problem?  I almost missed this notification as "junk mail".  I have communicated this to the owner of Batch (@scottkurz), so we'll get it resolved.

**Comment by scottkurz** [comment]
I think I addressed this in the 2nd commit, a7794e30216df46ed1b8dabf41ff0770981f9a81, I just pushed to https://github.com/jakartaee/specifications/pull/182.   I replaced the URL to an 'alt' text description.

**Comment by chrisguindon** [comment]
@kwsutter The Status section should already include a line for mixed content:

@netlify
Mixed content - jakartaee-specifications Successful in 6m — No mixed content detected

![Screen Shot 2020-06-09 at 1 13 27 PM](https://user-images.githubusercontent.com/893942/84178779-fd2f5800-aa52-11ea-9348-f97749e57076.png)

I don't seem to have an option to post this notification as a comment from netlify.

**Comment by kwsutter** [comment]
Thanks, @chrisguindon.  That should be sufficient for now.
