### ISSUE TITLE
[spec]SpecAssertions.html appear in two locations

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/specifications#245]
Hi,

I noticed that the [spec]SpecAssertions.html files appear to be checked-in in two locations. E.g.

* install/jacc/docs/assertions/spec/JACCSpecAssertions.html
* internal/docs/jacc/JACCSpecAssertions.html

I think this is highly confusing and very error prone. Can we delete one of those?

**Comment by pzygielo** [comment]
It's about files in [eclipse-ee4j/jakartaee-tck](https://github.com/eclipse-ee4j/jakartaee-tck), right?

**Comment by arjantijms** [comment]
> It's about files in eclipse-ee4j/jakartaee-tck, right?

True, maybe it's better to create the issues there.
