### ISSUE TITLE
Jakarta.ee Internal Broken Links

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/specifications#318]
As part of our ongoing SEO effort for Jakarta.EE, we need to fix broken links on the site.

Please fix the broken link listed in this report for jakarta.ee/specifications:
https://docs.google.com/spreadsheets/d/19FplHkHeqWlG5mPmuwhLN8YF0Fnr7s8-g-lW8Ez_hS8/edit?usp=sharing

Please let me know if you have any questions.

**Comment by ivargrimstad** [comment]
I'll bring it up to the spec committee. My initial comments:

### Row 2-36 
These are links internally in the released artifacts (HTML versions of spec documents and Javadoc). These cannot be updated without releasing a new version of the specification, so I guess we will need to file issues to the affected spec projects and let them fix it for their next release.

### Row 37 - 190
This is related to Chinese translations. I far as I recall, the spec committee has decided that translations for the specification pages would not be provided.

**Comment by kwsutter** [comment]
Where are we at with this Issue?  As @ivargrimstad pointed out, the first 2-36 rows need to be converted to separate Issues against the individual components.  Are we (spec committee) responsible for doing that, or will you be doing that @chrisguindon?

The Chinese translations are interesting.  There is also [this PR](https://github.com/jakartaee/specifications/pull/288) that is related to the Chinese translations.  I don't recall what our decision was with regards to this effort.

**Comment by chrisguindon** [comment]
I am hopeful that this something that the spec committee & community can take on. 

More than happy to help if there are technical hurdles with this request!

**Comment by chrisguindon** [comment]
Update:

I received an email by Excentric, the agency that created this report and they said that this was still an issue on the website.

They say that we need to fix broken internal links for Jakarta to help improve the site’s domain authority.

**Comment by lukasj** [comment]
issues in [xml binding spec](https://jakarta.ee/specifications/xml-binding/3.0/jakarta-xml-binding-spec-3.0.html) are covered in #340

issues in jsonp were fixed at source by https://github.com/eclipse-ee4j/jsonp/pull/272, update for the web (jsonp service release) will follow

**Comment by ivargrimstad** [comment]
I don't see any reason why we should keep this issue open any longer.
