### ISSUE TITLE
Release Jakarta Servlet TCK 5.0.1  + Jakarta EE Platform TCK 9.0.1 

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/specifications#321]
*Links to the TCK releases to be published:*

## EFTL bundles:
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.1.zip
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaee-tckinfo.txt
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-servlet-tck-5.0.1.zip
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-servlet-tck-5.0.1-tckinfo.txt

## FYI, EPL bundles:
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/promoted/jakartaeetck-9.0.1.zip
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/promoted/jakartaeetck-9.0.1-tckinfo.txt
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/promoted/servlet-tck-5.0.1.zip
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/promoted/servlet-tck-5.0.1-tckinfo.txt

## *Updated TCK links in the specification's _index.md file:*
Please update https://jakarta.ee/specifications/servlet/5.0/ to reference TCK (to be copied by spec team) https://download.eclipse.org/jakartaee/servlet/5.0/jakarta-servlet-tck-5.0.1.zip 

## *A high-level description of what tests were excluded from the TCK and why:*

1. [Accepted TCK challenge for `Cookie setMaxAgePositiveTest uses an overly strict Date format for the expires attribute`](https://github.com/eclipse-ee4j/servlet-api/issues/378)
2. [Accepted TCK challenge for `Test needs to be updated to 5.0 SPEC described behavior for async dispatch`](https://github.com/eclipse-ee4j/servlet-api/issues/385) 

## Excluded tests:
- [com.sun.ts.tests.servlet.api.jakarta_servlet_http.cookie.URLClient#setMaxAgePositiveTest](https://github.com/eclipse-ee4j/servlet-api/issues/378)
- [com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet_http.cookie.URLClient#setMaxAgePositiveTest](https://github.com/eclipse-ee4j/servlet-api/issues/378)
- [com.sun.ts.tests.servlet.api.jakarta_servlet_http.httpservletrequest40#httpServletMappingDispatchTest](https://github.com/eclipse-ee4j/servlet-api/issues/385)

## Pull requests to update the appropriate Specification pages with the updated TCKs:
- [Platform TCK 9.0.1]( https://github.com/jakartaee/specifications/pull/322)
- [Servlet TCK 5.0.1]( https://github.com/jakartaee/specifications/pull/323)

**Comment by scottmarlow** [comment]
Note that the above details are described in pull request https://github.com/jakartaee/jakarta.ee/pull/1018 which is for improving the TCK Process.

**Comment by scottmarlow** [comment]
After this issue is addressed and mentioned TCKs are released, the TCK challenge issues need to be closed:
- https://github.com/eclipse-ee4j/servlet-api/issues/385
- https://github.com/eclipse-ee4j/servlet-api/issues/378

**Comment by scottmarlow** [comment]
One more change is needed to the test exclusions.  I'll update this issue when the TCKs are updated.

**Comment by scottmarlow** [comment]
@kwsutter @ivargrimstad I was asked when the TCKs will be published.  Should this issue be assigned to someone specific that has permissions?

**Comment by kwsutter** [comment]
@scottmarlow You need to create PRs to update the appropriate Specification pages with the updated TCKs.  For example..

Platform:  https://github.com/jakartaee/specifications/tree/master/platform/9/_index.md
Servlet:  https://github.com/jakartaee/specifications/blob/master/servlet/5.0/_index.md  

These would need to point at the updated TCK along with the corresponding sig, sha, and pub values.

Once these PRs are approved and merged, then we just need to run the Jenkins promote-release job to get the TCKs promoted to the proper location.
https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ 

Hope this helps!

**Comment by scottmarlow** [comment]
Thank you @kwsutter!  I updated the bottom of the description to link to the appropriate Specification pages PRs (also see same links mentioned right above this comment).

**Comment by scottmarlow** [comment]
This issue can now be closed as https://download.eclipse.org/jakartaee/servlet/5.0/jakarta-servlet-tck-5.0.1.zip + https://download.eclipse.org/jakartaee/platform/9/jakarta-jakartaeetck-9.0.1.zip are published.

https://jakarta.ee/specifications/servlet/5.0/ + https://jakarta.ee/specifications/platform/9/ are updated to link to the ^ published TCKs.
