### ISSUE TITLE
Add new Compatible Implementation

### ISSUE THREAD

**Issue by Thihup** [jakartaee/specifications#326]
Is it possible to add a new Compatible Implementation to  https://github.com/jakartaee/specifications/blob/master/jsonp/2.0/_index.md or it is only possible if an implementation is ready at the time of the ballot? 

https://github.com/eclipse-ee4j/jsonp/issues/271#issuecomment-770882685

**Comment by keilw** [comment]
You have to prove compatibility first. IMO this can be closed, but I leave it to others to do that.

**Comment by Thihup** [comment]
That issue is enough to prove compatible or there is something more to do?

**Comment by keilw** [comment]
Not that I'm aware of, but the ballot has to run for a certain time, usually 2 weeks or more in the Spec Committee and only after it was succesful a change to those pages may happen.

**Comment by kwsutter** [comment]
@Thihup The [Specification page that you referenced](https://github.com/jakartaee/specifications/blob/master/jsonp/2.0/_index.md) is only for the initial approval ballot for JSONP.

The [additional Issue you created against the JSONP Specification Project](https://github.com/eclipse-ee4j/jsonp/issues/271#issuecomment-770882685) was the right way to go to register an additional Compatible Implementation.  @m0mus also confirmed this by the Acceptance tag and comment on that Issue.

Now, the next step is to figure out how to properly announce and display these additional Compatible Implementations for the individual Specifications.  As you know, we have the [Compatible Implementation page](https://jakarta.ee/compatibility/) for the overall Jakarta EE Platform.  But, we don't have a consistent means of displaying Compatible Implementations for individual Specifications.

I will add this to our Specification Committee's agenda and start that conversation.  We have talked about this situation, but I believe your request is the first one to push the item. Thank you!

**Comment by Thihup** [comment]
Sorry for all the confusion. I thought that the specification page would be the place because the title says "Compatible Implementations" (plural) and it is a very convenient place for a user who is looking forward to seeing the spec to also see the implementation.

@kwsutter Thanks for the detailed answer ;)

/cc @leadpony

**Comment by keilw** [comment]
Thanks @kwsutter for additional input especially about the compatible implementations page (which on the top level Jakarta EE says "Compatible Products" btw although not all implementations are commercial products) 
The links above only referred to GH project pages, but as Kevin said, the individual specs like https://jakarta.ee/specifications/jsonp/2.0/ contain a section for "Compatible Implementations" but that is a snapshot of the moment when the spec released a particular version and currently doesn't get updated if Spec X got another compatible implementation before its next release.

**Comment by kwsutter** [comment]
> Sorry for all the confusion.

No confusion, @Thihup!  Thanks for raising the question so that we can get this properly addressed.  I have already raised this question to the Specification Committee via email and hopefully make some progress on it before our next meeting.  Thanks again.

**Comment by Thihup** [comment]
According to the blog post of @ivargrimstad (https://www.agilejava.eu/2021/02/05/compatible-implementations/), it should be able to just open a PR adding the link. I'll do it and we can see what happens next.

**Comment by ivargrimstad** [comment]
Closed by https://github.com/jakartaee/specifications/pull/327
