### ISSUE TITLE
JavaDoc links broken at least for Security on Jakarta.ee

### ISSUE THREAD

**Issue by keilw** [jakartaee/specifications#388]
The JavaDoc links for Jakarta Security seem completely messed-up and broken both in version 1: https://jakarta.ee/specifications/security/1.0/apidocs
and 2: https://jakarta.ee/specifications/security/2.0/apidocs

**Comment by ivargrimstad** [comment]
They seem to work fine for me now. Could it be that you tried them while the site was being rebuilt yesterday. We had half an hour or so where the specifications pages were unavailable.

**Comment by lukasj** [comment]
https://jakarta.ee/specifications/platform/9.1/apidocs seems to be broken too - at least for me right now; I can see 3 frames each showing "404 Page Not Found"

**Comment by keilw** [comment]
https://jakarta.ee/specifications/security/2.0/apidocs still looks weird and pretty much unusable on a white page without CSS or anything else. I tried that in many different browsers including "private mode" so does not seem to be any caching either.

**Comment by arjantijms** [comment]
Same here, something is definitely not right there.

**Comment by ivargrimstad** [comment]
I have filed a bug for it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573726

**Comment by ivargrimstad** [comment]
I believe this one is fixed
