### ISSUE TITLE
Jakarta Persistence TCK 3.0.1 link broken

### ISSUE THREAD

**Issue by beikov** [jakartaee/specifications#397]
The link `https://download.eclipse.org/jakartaee/persistence/3.0/jakarta-persistence-tck-3.0.1.zip` on https://jakarta.ee/specifications/persistence/3.0/ does not work. Did anyone forget to upload the 3.0.1 version of the TCK?

**Comment by ivargrimstad** [comment]
I ran the promotion job, so the file is now available for download.

**Comment by beikov** [comment]
Thanks!
