### ISSUE TITLE
Package rename did not change directory

### ISSUE THREAD

**Issue by starksm64** [jakartaee/specifications#452]
I don't understand how this is compiling, but the current main branch has the tck packages under ee.jakarta.tck.faces.*, but the source directory is still using the old com.sun.faces.* location. This should not be compiling, but it is? I'll be fixing this.

**Comment by tjwatson** [comment]
> I don't understand how this is compiling, but the current main branch has the tck packages under ee.jakarta.tck.faces._, but the source directory is still using the old com.sun.faces._ location. This should not be compiling, but it is? I'll be fixing this.

Just to answer how.  I believe IDEs enforce this convention and will refuse to compile it but the actual `javac` compiler will go ahead and compile it.  It only cares about what the `package` statement says, not what directory the file is in.

**Comment by starksm64** [comment]
Right, but since we are using the maven-compiler-plugin to invoke javac, I thought that did not allow this? I have looked for a setting that would enforce the failure, but nothing is popping up. I am seeing indications that the maven-compiler-plugin will report a directory structure/package name mismatch.
