### ISSUE TITLE
Javadoc for Jakarta Authentication 3.0 is incomplete

### ISSUE THREAD

**Issue by bjhargrave** [jakartaee/specifications#500]
https://jakarta.ee/specifications/authentication/3.0/ links to https://jakarta.ee/specifications/authentication/3.0/apidocs which only has the javadoc for 1 of the 4 packages in the specification.

**Comment by bjhargrave** [comment]
cc: @arjantijms

**Comment by arjantijms** [comment]
@bjhargrave This is really insanely weird. Never saw something like this before, and I saw tons of forgotten or missing things. I re-generated the docs again here: https://github.com/jakartaee/specifications/pull/503

**Comment by arjantijms** [comment]
Packages seem to be back, but please double check for any other issues:

https://deploy-preview-503--jakartaee-specifications.netlify.app/specifications/authentication/3.0/apidocs/jakarta.security.auth.message/module-summary.html

**Comment by bjhargrave** [comment]
Thanks for the fix. The preview looks fine.
