### ISSUE TITLE
Release Jakarta Annotations TCK service release (2.1.1) due to recent change to deprecate @ManagedBean

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/specifications#517]
The staged Jakarta Annotations TCK (2.1.1) is available for release via https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-annotations-tck-2.1.1.zip.  

I validated locally that WildFly does pass the https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-annotations-tck-2.1.1.zip (see attached [annotationtck.log](https://github.com/jakartaee/specifications/files/8921870/annotationtck.log)).

To handle this request, please copy https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-annotations-tck-2.1.1.zip to the https://download.eclipse.org/jakartaee/annotations/2.1 folder so that Jakarta Annotations 2.1 implementations for the Jakarta EE 10 release, can ensure they have the correct Jakarta Annotations 2.1 SPEC API signatures.

**Comment by starksm64** [comment]
It has been promoted:
```
https://download.eclipse.org/jakartaee/annotations/2.1/jakarta-annotations-tck-2.1.1.zip
└> cat /tmp/jakarta-annotations-tck-2.1.1.zip.sha256 
8c2131d51c75cde4be74382f662519f9fd439f4ce4dd60832ed55b796e5f72f3
```
