### ISSUE TITLE
Jakarta EE CDI spec page uses three different names

### ISSUE THREAD

**Issue by ljnelson** [jakartaee/specifications#536]
https://jakarta.ee/specifications/cdi/ has the title "Jakarta Contexts and Dependency Injection".  That seems right.

Then each subheading on that page says "Jakarta Context Dependency Injection".  That seems wrong.

Navigating to https://jakarta.ee/specifications/cdi/4.0/ (haven't tried the earlier versions, but I'm guessing something is generating the boilerplate so this problem is probably on other pages as well), I see:

* Jakarta Context Dependency Injection
* Jakarta Contexts Dependency Injection
* Jakarta Contexts and Dependency Injection

…in the text.

I assume "Jakarta Contexts and Dependency Injection" is actually the proper name of the specification, since the others do not show up in the [specification itself](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html).

**Comment by ivargrimstad** [comment]
Fixed
