### ISSUE TITLE
Jakarta EE 10 javadocs do not display frameset. Jakarta EE 10 docs do.

### ISSUE THREAD

**Issue by edburns** [jakartaee/specifications#605]
Compare the rendering of these two pages in separate browser windows.

* https://jakarta.ee/specifications/platform/10/apidocs/index.html
* https://jakarta.ee/specifications/platform/9/apidocs/index.html

You will see that the 9 version correctly shows the frameset, but the 10 version does not. At first I thought this was related to [PR 1640](https://github.com/jakartaee/jakarta.ee/pull/1640), but it seems not.

I compared the HTTP headers returned and they both have the same value for **Content-Security-Policy**

```
content-security-policy: default-src https: 'unsafe-eval' 'unsafe-inline'; object-src 'none'; frame-ancestors 'self'; img-src https: data:
```

There must be something else wrong.

I'd like to link the 10 Javadocs to https://aka.ms/java/ee but I want to wait for this to be fixed before doing it.

**Comment by edburns** [comment]
Hello @hussainnm , any idea on this?

**Comment by kazumura** [comment]
@edburns 
Jakarta EE 10 apidocs are genereted by javadoc of Java 11, while Jakarta EE 9 by Java 8.  
javadoc of Java 11 does not generate frames by default. Please see https://bugs.openjdk.org/browse/JDK-8202961 .

**Comment by ivargrimstad** [comment]
I guess we can close this one?
