### ISSUE TITLE
Adding Google Analytics

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/specifications#670]
I think this issue may need to be moved but I wasn't sure where to put it.

Shabnam an I realized last week that the actual specification docs do not have google analytics implemented, eg:

https://jakarta.ee/specifications/platform/10/jakarta-platform-spec-10.0
https://jakarta.ee/specifications/webprofile/10/jakarta-webprofile-spec-10.0
https://jakarta.ee/specifications/activation/2.0/jakarta-activation-spec-2.0

Is it possible to get that added on all of the official doc pages?

Link to GTM tag needed: https://www.eclipse.org/eclipse.org-common/themes/solstice/docs/#gdpr

**Comment by excentrickristy** [comment]
Is there any update on this?

**Comment by ivargrimstad** [comment]
The existing specification documents will not be updated unless they are part of a formal release. This is not likely to happen. We may investigate if it is possible to add an analytics link to future documents produced by upcoming releases.

Please provide the HTML snippet required so we can ask the specification projects to include, if possible, in future releases.

**Comment by excentrickristy** [comment]
Ok, thanks for the insight, I will report back to the marketing committee!
