### ISSUE TITLE
Link for CI Eclipse OpenMQ 6.3.0-RC1 in https://jakarta.ee/specifications/messaging/3.1/ is broken

### ISSUE THREAD

**Issue by kenliao94** [jakartaee/specifications#786]
The link https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/mq/mq-distribution/6.3.0-RC1/mq-distribution-6.3.0-RC1.zip is broken and I can't download a CI for Jakarta Messaging 3.1

**Comment by pzygielo** [comment]
- OpenMQ 6.4.0 [GitHub Release](https://github.com/eclipse-ee4j/openmq/releases/tag/6.4.0-RELEASE)/[Central](https://repo.maven.apache.org/maven2/org/glassfish/mq/mq-distribution/6.4.0/) was accepted for Messaging 3.1 https://github.com/jakartaee/messaging/issues/329 as well
