### ISSUE TITLE
Update the Jakarta EE API jar dependencies

### ISSUE THREAD

**Issue by starksm64** [jakartaee/specifications#90]
Update the Jakarta EE API jar by submitting a PR against the https://github.com/eclipse-ee4j/jakartaee-api project that updates the version number of your API jar file.

  - [x] Jakarta Annotations
  - [x] Jakarta Concurrency
  - [x] Jakarta Expression Language
  - [x] Jakarta Managed Beans - N/A (provided via Annotations API)
  - [x] Jakarta XML Registries
  - [x] Jakarta Deployment
  - [x] Jakarta Bean Validation
  - [x] Jakarta Messaging
  - [x] Jakarta Persistence
  - [x] Jakarta JSON Processing
  - [x] Jakarta Servlet
  - [x] Jakarta WebSocket
  - [x] Jakarta Dependency Injection
  - [x] Jakarta Interceptors
  - [x] Jakarta Authorization
  - [x] Jakarta XML RPC
  - [x] Jakarta Authentication
  - [x] Jakarta Mail
  - [x] Jakarta JSON Binding
  - [x] Jakarta Server Pages
  - [x] Jakarta Debugging Support for Other Languages
  - [x] Jakarta Contexts and Dependency Injection
  - [x] Jakarta Batch
  - [x] Jakarta RESTful Web Services
  - [x] Jakarta Transactions
  - [x] Jakarta Enterprise Beans
  - [x] Jakarta Connectors
  - [x] Jakarta Standard Tag Library
  - [x] Jakarta Security
  - [x] Jakarta Server Faces
  - [x] Jakarta Management

**Comment by gunnarmorling** [comment]
Can't check the box, but for BV the update PR is here: https://github.com/eclipse-ee4j/jakartaee-api/pull/31

**Comment by starksm64** [comment]
Issue check box has been updated, thanks.

**Comment by kwsutter** [comment]
Just updated Managed Beans checkbox (covered with Annotations, which is already complete).

**Comment by kwsutter** [comment]
I pinged @arjantijms for Server Faces 2.3.2 and @ren-zhijun-oracle for JSTL 1.2.7.  If I don't get it by tomorrow, I will go ahead with my own PR.

**Comment by kwsutter** [comment]
The last two were covered by [PR #34](https://github.com/eclipse-ee4j/jakartaee-api/pull/34).  I also updated the JACC GAV due to the 1.5 version issue.  I think this is now done.
